[package]
name = "revival"
version = "0.1.0"
description = "Revival Minecraft Launcher Backend"
authors = ["Revival Developers"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
dirs = "5.0"
zip = "0.6"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[features]
# by default tauri runs in production mode
# this feature is used for development builds
custom-protocol = ["tauri/custom-protocol"]
